### ISSUE TITLE
Error with CMakeLists USE_CYCLUS

### ISSUE THREAD

**Issue by emmaredfoot** [emmaredfoot/hybrid#15]
/usr/bin/cmake
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success

CMAKE_MODULE_PATH /share/cmake-2.8/Modules;/home/emma/github/cyclus/hybrid/cmake
-- Using /home/emma/.local as CYCLUS_ROOT_DIR.
-- Dependency Cyclus (DEPS_CYCLUS): 
-- Dependency Library Cyclus (DEPS_LIB_CYCLUS): 
-- Dependency Share Cyclus (DEPS_SHARE_CYCLUS): 
-- Dependency Include Cyclus (DEPS_INCLUDE_CYCLUS): 
-- Found Cyclus Core Headers : /home/emma/.local/include/cyclus
-- Found Cyclus Core Test Headers : /home/emma/.local/include/cyclus
-- Found Cyclus Core Shared Data : /home/emma/.local/share/cyclus
-- Found Cyclus Core Library : /home/emma/.local/lib/libcyclus.so
-- Found Cyclus Test Libraries : /home/emma/.local/lib/cyclus/libgtest.so/home/emma/.local/lib/cyclus/libbaseagentunittests.so
--LD_LIBRARY_PATH: 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
--    HDF5 Root: 
--    HDF5 Include directory: 
--    HDF5 Library directories: 
--    HDF5 Libraries: 
CMake Error at src/CMakeLists.txt:2 (USE_CYCLUS):
  Unknown CMake command "USE_CYCLUS".

-- Configuring incomplete, errors occurred!
See also "/home/emma/github/cyclus/hybrid/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "install.py", line 137, in <module>
    main()
  File "install.py", line 134, in main
    install(args)
  File "install.py", line 62, in install
    shell=(os.name == 'nt'))
  File "/home/emma/anaconda3/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/emma/github/cyclus/hybrid', '-DCMAKE_INSTALL_PREFIX=/home/emma/

**Comment by katyhuff** [comment]
@emmaredfoot Did we fix this when you were in town? I think this issue can be closed, right?
